---
- name: Reload systemd
  ansible.builtin.systemd:
    daemon_reload: true
  listen: postgres_exporter reload systemd

- name: Restart postgres_exporter
  ansible.builtin.service:
    name: postgres_exporter
    state: restarted
  listen: postgres_exporter restart
