---
- name: Install haproxy package
  ansible.builtin.include_tasks: "install-{{ _pg_os_variant }}.yml"

- name: Ensure haproxy config directory exists
  ansible.builtin.file:
    path: /etc/haproxy
    state: directory
    owner: root
    group: root
    mode: "0755"
