---
- name: Restart postgresql
  ansible.builtin.service:
    name: "{{ postgresql_service }}"
    state: restarted

- name: Reload postgresql
  ansible.builtin.service:
    name: "{{ postgresql_service }}"
    state: reloaded
