---
- name: Restart unattended-upgrades
  ansible.builtin.systemd:
    name: unattended-upgrades
    state: restarted

- name: Restart apt-daily-upgrade timer
  ansible.builtin.systemd:
    name: apt-daily-upgrade.timer
    state: restarted
    daemon_reload: true
