---
- name: Reload systemd
  ansible.builtin.systemd:
    daemon_reload: true
  listen: node_exporter reload systemd

- name: Restart node_exporter
  ansible.builtin.service:
    name: node_exporter
    state: restarted
  listen: node_exporter restart
